In [39]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [40]:
# Import the dataset:

df=pd.read_csv(r'D:\RegAnalysis - Project\Project 2\Class Apr-May 2018.csv')
df1=pd.read_csv(r'D:\RegAnalysis - Project\Project 2\Class june 2018.csv')

In [42]:
# Checking on the various features with our Target variable (Numbers booked)

df.head(20)
df.shape

df1.head(20)
df1.shape

,ActivitySiteID,ActivityDescription,BookingEndDateTime (Month / Day / Year),BookingStartTime,MaxBookees,Number Booked,Price (INR)
0,HXP,20-20-20 2.45pm-3.45pm,08-Apr-18,14:45:00,25,12,499.0
1,HXP,20-20-20 2.45pm-3.45pm,15-Apr-18,14:45:00,25,15,499.0
2,HXP,20-20-20 2.45pm-3.45pm,22-Apr-18,14:45:00,25,14,499.0
3,HXP,20-20-20 2.45pm-3.45pm,29-Apr-18,14:45:00,25,9,499.0
4,HXP,20-20-20 2.45pm-3.45pm,06-May-18,14:45:00,25,7,499.0
5,HXP,20-20-20 2.45pm-3.45pm,13-May-18,14:45:00,25,10,499.0
6,HXP,20-20-20 2.45pm-3.45pm,20-May-18,14:45:00,25,7,499.0
7,HXP,20-20-20 2.45pm-3.45pm,27-May-18,14:45:00,25,3,499.0
8,TSC,20-20-20 7.00-8.00pm,04-Apr-18,19:00:00,24,10,499.0
9,TSC,20-20-20 7.00-8.00pm,11-Apr-18,19:00:00,24,12,499.0
10,TSC,20-20-20 7.00-8.00pm,18-Apr-18,19:00:00,24,9,499.0
11,TSC,20-20-20 7.00-8.00pm,25-Apr-18,19:00:00,24,5,499.0
12,TSC,20-20-20 7.00-8.00pm,02-May-18,19:00:00,24,6,499.0
13,TSC,20-20-20 7.00-8.00pm,09-May-18,19:00:00,24,5,499.0
14,TSC,20-20-20 7.00-8.00pm,16-May-18,19:00:00,24,6,499.0
15,TSC,20-20-20 7.00-8.00pm,23-May-18,19:00:00,24,6,499.0
16,TSC,20-20-20 7.00-8.00pm,30-May-18,19:00:00,24,7,499.0
17,NBL,20-20-20 9.30-10.30am,03-Apr-18,09:30:00,60,42,499.0
18,NBL,20-20-20 9.30-10.30am,10-Apr-18,09:30:00,60,34,499.0
19,NBL,20-20-20 9.30-10.30am,17-Apr-18,09:30:00,60,37,499.0

In [43]:
# Since both datasets have similar colums we can stack them using concat

df2=pd.concat([df, df1], ignore_index=True)

In [44]:
df2.head()
df2.shape

(3289, 7)

In [45]:
# Data Cleaning and Pre-processing:

#Handling null values:

df2.isnull().sum()

ActivitySiteID                              0
ActivityDescription                         0
BookingEndDateTime (Month / Day / Year)     0
BookingStartTime                            0
MaxBookees                                  0
Number Booked                               0
Price (INR)                                18
dtype: int64

In [46]:
## Impute the Price(INR) using median:

df2['Price (INR)']= df2['Price (INR)'].fillna(df2['Price (INR)'].median())

In [47]:
df2.isnull().sum()

ActivitySiteID                             0
ActivityDescription                        0
BookingEndDateTime (Month / Day / Year)    0
BookingStartTime                           0
MaxBookees                                 0
Number Booked                              0
Price (INR)                                0
dtype: int64

In [48]:
# Obeserving the datatypes of the variables:
df2.dtypes

ActivitySiteID                              object
ActivityDescription                         object
BookingEndDateTime (Month / Day / Year)     object
BookingStartTime                            object
MaxBookees                                   int64
Number Booked                                int64
Price (INR)                                float64
dtype: object

In [49]:
df2['ActivitySiteID'].value_counts().reset_index

<bound method Series.reset_index of ActivitySiteID
HXP    771
SBP    731
BRP    727
TSC    531
NBL    529
Name: count, dtype: int64>

In [50]:
# Combining the columns BookingEndDateTime (Month / Day / Year) & BookingStartTime to Change the datatype into .datetime() format:

combined_string = df2['BookingEndDateTime (Month / Day / Year)']+' '+df2['BookingStartTime']
combined_string

0       08-Apr-18 14:45:00
1       15-Apr-18 14:45:00
2       22-Apr-18 14:45:00
3       29-Apr-18 14:45:00
4       06-May-18 14:45:00
               ...
3284    18-Jun-18 18:30:00
3285    25-Jun-18 18:30:00
3286    07-Jun-18 18:00:00
3287    14-Jun-18 18:00:00
3288    21-Jun-18 18:00:00
Length: 3289, dtype: object

In [52]:
df2['Full_datetime']=pd.to_datetime(combined_string, format='mixed')
df2.head()

,ActivitySiteID,ActivityDescription,BookingEndDateTime (Month / Day / Year),BookingStartTime,MaxBookees,Number Booked,Price (INR),Full_datetime
0,HXP,20-20-20 2.45pm-3.45pm,08-Apr-18,14:45:00,25,12,499.0,2018-04-08 14:45:00
1,HXP,20-20-20 2.45pm-3.45pm,15-Apr-18,14:45:00,25,15,499.0,2018-04-15 14:45:00
2,HXP,20-20-20 2.45pm-3.45pm,22-Apr-18,14:45:00,25,14,499.0,2018-04-22 14:45:00
3,HXP,20-20-20 2.45pm-3.45pm,29-Apr-18,14:45:00,25,9,499.0,2018-04-29 14:45:00
4,HXP,20-20-20 2.45pm-3.45pm,06-May-18,14:45:00,25,7,499.0,2018-05-06 14:45:00

In [53]:
# Checking on changed column:

df2.dtypes

ActivitySiteID                                     object
ActivityDescription                                object
BookingEndDateTime (Month / Day / Year)            object
BookingStartTime                                   object
MaxBookees                                          int64
Number Booked                                       int64
Price (INR)                                       float64
Full_datetime                              datetime64[ns]
dtype: object

In [54]:
## Finding the duplicate values:

df2.duplicated().sum()

np.int64(0)

In [56]:
df2.isnull().sum().index

Index(['ActivitySiteID', 'ActivityDescription',
       'BookingEndDateTime (Month / Day / Year)', 'BookingStartTime',
       'MaxBookees', 'Number Booked', 'Price (INR)', 'Full_datetime'],
      dtype='object')

In [61]:
## Feature Engineering:

df2['Hour']=df2['Full_datetime'].dt.hour
df2['DayOfWeek']=df2['Full_datetime'].dt.day_name()

In [63]:
print(df2[['Full_datetime', 'Hour', 'DayOfWeek']].head())

        Full_datetime  Hour DayOfWeek
0 2018-04-08 14:45:00    14    Sunday
1 2018-04-15 14:45:00    14    Sunday
2 2018-04-22 14:45:00    14    Sunday
3 2018-04-29 14:45:00    14    Sunday
4 2018-05-06 14:45:00    14    Sunday

In [66]:
df2.columns

Index(['ActivitySiteID', 'ActivityDescription',
       'BookingEndDateTime (Month / Day / Year)', 'BookingStartTime',
       'MaxBookees', 'Number Booked', 'Price (INR)', 'Full_datetime', 'Hour',
       'DayOfWeek'],
      dtype='object')

In [65]:
df2.head()

,ActivitySiteID,ActivityDescription,BookingEndDateTime (Month / Day / Year),BookingStartTime,MaxBookees,Number Booked,Price (INR),Full_datetime,Hour,DayOfWeek
0,HXP,20-20-20 2.45pm-3.45pm,08-Apr-18,14:45:00,25,12,499.0,2018-04-08 14:45:00,14,Sunday
1,HXP,20-20-20 2.45pm-3.45pm,15-Apr-18,14:45:00,25,15,499.0,2018-04-15 14:45:00,14,Sunday
2,HXP,20-20-20 2.45pm-3.45pm,22-Apr-18,14:45:00,25,14,499.0,2018-04-22 14:45:00,14,Sunday
3,HXP,20-20-20 2.45pm-3.45pm,29-Apr-18,14:45:00,25,9,499.0,2018-04-29 14:45:00,14,Sunday
4,HXP,20-20-20 2.45pm-3.45pm,06-May-18,14:45:00,25,7,499.0,2018-05-06 14:45:00,14,Sunday

In [67]:
df2.dtypes

ActivitySiteID                                     object
ActivityDescription                                object
BookingEndDateTime (Month / Day / Year)            object
BookingStartTime                                   object
MaxBookees                                          int64
Number Booked                                       int64
Price (INR)                                       float64
Full_datetime                              datetime64[ns]
Hour                                                int32
DayOfWeek                                          object
dtype: object

In [81]:
df2['Hour'] = df2['Hour'].astype(str)

In [82]:
# Encoding the following columns:

df2_dummies = pd.get_dummies(df2, columns=['ActivitySiteID', 'DayOfWeek', 'Hour'], dtype=int, drop_first=True)
df2_dummies.head()

,ActivityDescription,BookingEndDateTime (Month / Day / Year),BookingStartTime,MaxBookees,Number Booked,Price (INR),Full_datetime,ActivitySiteID_HXP,ActivitySiteID_NBL,ActivitySiteID_SBP,...,Hour_15,Hour_16,Hour_17,Hour_18,Hour_19,Hour_20,Hour_6,Hour_7,Hour_8,Hour_9
0,20-20-20 2.45pm-3.45pm,08-Apr-18,14:45:00,25,12,499.0,2018-04-08 14:45:00,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,20-20-20 2.45pm-3.45pm,15-Apr-18,14:45:00,25,15,499.0,2018-04-15 14:45:00,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,20-20-20 2.45pm-3.45pm,22-Apr-18,14:45:00,25,14,499.0,2018-04-22 14:45:00,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,20-20-20 2.45pm-3.45pm,29-Apr-18,14:45:00,25,9,499.0,2018-04-29 14:45:00,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,20-20-20 2.45pm-3.45pm,06-May-18,14:45:00,25,7,499.0,2018-05-06 14:45:00,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [89]:
# Feature selection:

x = df2_dummies.drop(columns=['Number Booked','ActivityDescription','BookingEndDateTime (Month / Day / Year)','BookingStartTime','Full_datetime'])
y = df2_dummies['Number Booked']

In [90]:
# To split the train and test data:

from sklearn.model_selection import train_test_split

In [92]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)
print('x_train',x_train.shape)
print('x_test',x_test.shape)
print('y_train',y_train.shape)
print('y_test',y_test.shape)

x_train (2302, 26)
x_test (987, 26)
y_train (2302,)
y_test (987,)

In [93]:
print([col for col in x_train.columns if 'Hour' in col])

['Hour_11', 'Hour_12', 'Hour_13', 'Hour_14', 'Hour_15', 'Hour_16', 'Hour_17', 'Hour_18', 'Hour_19', 'Hour_20', 'Hour_6', 'Hour_7', 'Hour_8', 'Hour_9']